Stat svc
RailgunSinon/java-explore-with-me pull request #3
Opened 2023-07-09 18:17 UTC by RailgunSinon

Первая итерация статистики.

2023-07-10 19:03 UTC, Donald522 requested changes
Привет!

Написал замечания.

2023-07-10 19:03 UTC, Donald522 commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/service/StatsServiceImpl.java
> +        log.info("Получен запрос сохранения статистики");
Уже же есть лог в контроллере
Ну и надо определиться с языком логирования.

2023-07-10 19:03 UTC, Donald522 commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/service/StatsServiceImpl.java
> +    private Integer createViewStateDto(Integer code, StateViewDto stateViewDto, List<Hit> hits,
Группировку надо в базе делать

2023-07-10 19:03 UTC, Donald522 commented on stat-service/stat-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS hits (
Не хватает индексов на uri и created

2023-07-11 15:09 UTC, RailgunSinon commented on stat-service/stat-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS hits (
> Не хватает индексов на uri и created

Постоянно забываю про индексы. Постараюсь исправиться.

2023-07-11 15:10 UTC, RailgunSinon commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/service/StatsServiceImpl.java
> +        log.info("Получен запрос сохранения статистики");
> Уже же есть лог в контроллере Ну и надо определиться с языком логирования.

убрал лишний, будет английский

2023-07-11 15:48 UTC, RailgunSinon commented on stat-service/stat-client/src/main/java/ru/practicum/explorewithme/statserver/StatClient.java
> +    public ResponseEntity<List<StateViewDto>> stats(String start, String end,
> Тут форматирование какое-то странное

Я в упор возможно не вижу странностей. Форматирование то же, что и было до этого, я через автоформатирование IDEA это делаю. Ничего не менял в системе, файл настроек форматирования тот же. Что именно ты имеешь в виду под странностями, можешь пояснить? Я поменял конкретно тут что резало глаз, он перенес странно, пришлось руками перенести

2023-07-11 16:01 UTC, RailgunSinon commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/service/StatsServiceImpl.java
> +        Boolean unique) {
> У тебя во многих местах такое форматирование Это специально так? Так не пишут.

Я в упор не вижу странности, Я переносил проект из-за глюка idea, может в этом дело.

2023-07-11 20:33 UTC, RailgunSinon commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/service/StatsServiceImpl.java
> +    private Integer createViewStateDto(Integer code, StateViewDto stateViewDto, List<Hit> hits,
> Группировку надо в базе делать

Я могу вынести только группировку в следующей итерации. Но тогда нужна отдельная сущность Просто под вынос, что для меня странно - нагромождение. Для "Умного" решения нужно JPQL + Constructor Expressions, в теории яндекс об этом ни слова и с наскока эту тему у меня обыграть не получилось. Я оставил закомментированную заготовку как я это вижу, но оно сыпется и не поднимается вообще, а дипломное время поджимает. Постараюсь решить вопрос к концу 2 сервиса, но не знаю, насколько это будет сложно, ибо опять таки ничего похожего нам не давали, сухо прошлись по обычному JPA + Query

2023-07-11 20:55 UTC, RailgunSinon commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/service/StatsServiceImpl.java
> +    private Integer createViewStateDto(Integer code, StateViewDto stateViewDto, List<Hit> hits,
> JPQL + Constructor Expressions

А ещё у бута сложные отношения с нстроечным файлом. Он его игнорирует, и фабрику для Entity manager нужно тоже создавать программно.

2023-07-12 11:08 UTC, RailgunSinon commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/service/StatsServiceImpl.java
> +    private Integer createViewStateDto(Integer code, StateViewDto stateViewDto, List<Hit> hits,
Победил с помощью товарища. Слишком усложнял, короче, можно конструктор в query передавать влоб оказывается.

2023-07-12 11:09 UTC, RailgunSinon commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/service/StatsServiceImpl.java
> +        Boolean unique) {
> У тебя во многих местах такое форматирование Это специально так? Так не пишут.

Если не исправилось форматирование, напиши, и я поправлю когда буду мейн сервис заливать. А то после победы над JPA зависнуть на форматировании грустно

2023-07-12 20:23 UTC, Donald522 approved these changes

2023-07-12 20:23 UTC, Donald522 commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/storage/HitRepository.java
> +    List<StateViewDto> findHitsNoUniq(LocalDateTime start, LocalDateTime end, List<String> uris);
Репозиторий не должен возвращать dto модель

2023-07-12 20:23 UTC, Donald522 commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/service/StatsServiceImpl.java
> +        Boolean unique) {
Ну за форматирование я конечно не буду отправлять на следующий круг) Это дело вкуса и договоренностей внутри конкретной команды.

Но я видел в основном такой подход:

```
public List<StateViewDto> stats(
  LocalDateTime start,
  LocalDateTime end,
  List<String. uris,
  Boolean unique
) {
...
}

2023-07-12 20:24 UTC, Donald522 commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/service/StatsServiceImpl.java
> +    private Integer createViewStateDto(Integer code, StateViewDto stateViewDto, List<Hit> hits,
Тут много каких-то умных слов, я даже не все знаю из них)

На мой взгляд, если фреймворк усложняет тебе жизнь - от него отказаться.

2023-07-12 21:17 UTC, RailgunSinon commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/service/StatsServiceImpl.java
> +        Boolean unique) {
> Ну за форматирование я конечно не буду отправлять на следующий круг) Это дело вкуса и договоренностей внутри конкретной команды.
> 
> Но я видел в основном такой подход:
> 
> ```
> public List<StateViewDto> stats(
>   LocalDateTime start,
>   LocalDateTime end,
>   List<String. uris,
>   Boolean unique
> ) {
> ...
> }
> ```

Приму к сведению. Я попробовал так сделать и автоформатирование все вернуло =/

2023-07-12 21:19 UTC, RailgunSinon commented on stat-service/stat-server/src/main/java/ru/practicum/explorewithme/statserver/storage/HitRepository.java
> +    List<StateViewDto> findHitsNoUniq(LocalDateTime start, LocalDateTime end, List<String> uris);
> Репозиторий не должен возвращать dto модель

Ок, я попробую на следующей смене/итерации придумать, как тогда это сделать. Но тогда придётся плодить доп. сущность, не знаю насколько оправдано.

2023-07-12 21:20 UTC, merged